use_frameworks!
 platform :ios, '11.0'
target 'ZPTesting_Example' do

  target 'ZPTesting_Tests' do
    	inherit! :search_paths
  end

end

target 'ZPTesting_ExampleUITests' do
  inherit! :search_paths
	pod 'ZPTesting', :path => '../'
end
